#!/bin/sh

stowFolders=$(cat<<EOF
hypr
waybar
zsh
nvim
wezterm
alacritty
bin
EOF
)
echo "$stowFolders" | while IFS= read -r folder; do
    echo "stow $folder"
    stow -t $HOME -D $folder
    stow -t $HOME $folder
done
