local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fa',  function() builtin.find_files({ no_ignore = true, prompt_title = 'All Files' }) end, {})
vim.keymap.set('n', '<leader>fr',  function() builtin.lsp_references({ no_ignore = true, prompt_title = 'LSP References' }) end, {})
vim.keymap.set('n', '<leader>fd',  function() builtin.lsp_document_symbols({ no_ignore = true, prompt_title = 'LSP References' }) end, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
